services:
    hbpf.orm_role.fixture:
        class: Hanaboso\AclBundle\DataFixtures\ORM\RoleFixtures
        tags:
            - { name: doctrine.fixture.orm }

    hbpf.acl.provider:
        class: Hanaboso\AclBundle\Provider\Impl\AclProvider
        arguments:
            - '@hbpf.database_manager_locator'
            - '@hbpf.user.provider.resource'
            - '%resource_enum%'
            - '@hbpf.acl.cache.null' #hbpf.acl.cache.redis|hbpf.acl.cache.null

    hbpf.acl.cache.null:
        class: Hanaboso\AclBundle\Cache\NullCache

    hbpf.acl.cache.redis:
        class: Hanaboso\AclBundle\Cache\RedisCache
        arguments:
            - '%env(string:REDIS_DSN)%'