version: '3.5'
services:
    app:
        image: hanabosocom/php-dev:php-8.3-alpine
        user: ${DEV_UID}:${DEV_GID}
        volumes:
            - ./:/var/www:cached
            - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached
        environment:
            - APP_ENV=dev
            - DEV_UID=${DEV_UID}
            - DEV_GID=${DEV_GID}
            - KERNEL_CLASS=AclBundleTests\Kernel
            - COMPOSER_HOME=${HOME}/dev/.composer
            - SMTP_DSN=${SMTP_DSN}
            - REDIS_DSN=redis://redis/10
            - MONGODB_DSN=mongodb://mongo
            - MONGODB_DB=acl
            - MARIADB_DSN=mariadb
            - MARIADB_DB=acl
            - MARIADB_USER=root
            - MARIADB_PASS=root

    mongo:
        image: mongo:latest
        volumes:
            - mongo:/data/db

    mariadb:
        image: mariadb:10
        command: "mysqld --innodb_flush_method=nosync"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mariadb:/var/lib/mysql

    redis:
        image: redis:alpine

volumes:
    mongo: {}
    rabbit-mq: {}
    mariadb: {}
