version: '3.5'
services:
    app:
        image: hanabosocom/php-dev:php-7.4-alpine
        user: ${DEV_UID}:${DEV_GID}
        volumes:
            - ./:/var/www:cached
            - ${SSH_AUTH}:/tmp/.ssh-auth-sock
            - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached
        environment:
            - APP_ENV=dev
            - DEV_UID=${DEV_UID}
            - DEV_GID=${DEV_GID}
            - KERNEL_CLASS=AclBundleTests\Kernel
            - COMPOSER_HOME=${HOME}/dev/.composer
            - SMTP_HOST=${SMTP_HOST}
            - SMTP_PORT=${SMTP_PORT}
            - SMTP_USER=${SMTP_USER}
            - SMTP_PASSWORD=${SMTP_PASSWORD}
            - REDIS_DSN=redis://redis/10
            - MONGODB_DSN=mongodb://mongo
            - MONGODB_DB=acl
            - MARIADB_DSN=mariadb
            - MARIADB_DB=acl
            - MARIADB_USER=root
            - MARIADB_PASS=root

    mongo:
        image: mongo:latest
        volumes:
            - mongo:/data/db

    rabbitmq:
        image: rabbitmq:management-alpine
        volumes:
            - rabbit-mq:/var/lib/rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
            - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}

    mariadb:
        image: mariadb:latest
        command: "mysqld --innodb_flush_method=nosync"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mariadb:/var/lib/mysql

    redis:
        image: redis:alpine

volumes:
    mongo: {}
    rabbit-mq: {}
    mariadb: {}
