version: '3.3'
services:
    app:
        image: hanabosocom/php-dev:php-7.3
        user: ${DEV_UID}:${DEV_GID}
        volumes:
            - ./:/var/www
            - ${SSH_AUTH_SOCK}:${SSH_AUTH}
            - ${HOME}/.composer:/srv/.composer
        environment:
            - APP_ENV=dev
            - DEV_UID=${DEV_UID}
            - DEV_GID=${DEV_GID}
            - KERNEL_CLASS=AclBundleTests\Kernel
            - SMTP_TRANSPORT=${SMTP_TRANSPORT}
            - SMTP_HOST=${SMTP_HOST}
            - SMTP_PORT=${SMTP_PORT}
            - SMTP_USER=${SMTP_USER}
            - SMTP_PASSWORD=${SMTP_PASSWORD}

    mongo:
        image: mongo:latest
        volumes:
            - mongo:/data/db

    rabbitmq:
        image: rabbitmq:management-alpine
        volumes:
            - rabbit-mq:/var/lib/rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
            - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}

    mariadb:
        image: mariadb:latest
        command: "mysqld --innodb_flush_method=nosync"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mariadb:/var/lib/mysql

    redis:
        image: redis:alpine

volumes:
    mongo: {}
    rabbit-mq: {}
    mariadb: {}
