services:
    _defaults:
        public: '%public.services%'

    hbpf.factory.rule:
        class: Hanaboso\AclBundle\Factory\RuleFactory
        arguments:
            - '@hbpf.database_manager_locator'
            - '@hbpf.user.provider.resource'
            - '@hbpf.factory.mask'
            - '%acl_rule%'
            - '%resource_enum%'

    hbpf.access.manager:
        class: Hanaboso\AclBundle\Manager\AccessManager
        arguments:
            - '@hbpf.database_manager_locator'
            - '@hbpf.factory.rule'
            - '@hbpf.factory.mask'
            - '@hbpf.acl.provider'
            - '@hbpf.user.provider.resource'
            - '%resource_enum%'
            - '%action_enum%'
        tags:
            - { name: kernel.event_subscriber }

    hbpf.manager.user:
        class: Hanaboso\AclBundle\Manager\UserManager
        arguments:
            - '@hbpf.access.manager'
        tags:
            - { name: kernel.event_subscriber }

    hbpf.manager.group:
        class: Hanaboso\AclBundle\Manager\GroupManager
        arguments:
            - '@hbpf.database_manager_locator'
            - '@hbpf.user.provider.resource'
            - '@hbpf.acl.provider'

    hbpf.factory.mask:
        class: Hanaboso\AclBundle\Factory\MaskFactory
        arguments:
            - '%action_enum%'
            - '%resource_enum%'
            - '%resource_actions%'
